import { PRODUCT, FormField } from "@/types/product";
import { Sparkles } from 'lucide-react';

export const BLOG_FORM = [
  {
    id: '1',
    inputType: 'input',
    placeholder: 'Enter Blog Title',
    name: 'blog_title',
    label: 'Blog Title',
    maxLength: 100,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '2',
    inputType: 'select',
    placeholder: 'Select Commentable Option',
    name: 'blog_commentable',
    label: 'Blog Commentable',
    options: [
      { label: 'Moderate', value: 'moderate' },
      { label: 'No', value: 'no' },
      { label: 'Yes', value: 'yes' },
    ],
  },
  {
    id: '3',
    inputType: 'input',
    placeholder: 'Enter Feedburner URL',
    name: 'blog_feedburner',
    label: 'Blog Feedburner',
    type: 'text',
  },
  {
    id: '4',
    inputType: 'input',
    placeholder: 'Enter Feedburner Location',
    name: 'blog_feedburner_location',
    label: 'Blog Feedburner Location',
    type: 'text',
  },
  {
    id: '5',
    inputType: 'input',
    placeholder: 'Enter Handle',
    name: 'blog_handle',
    label: 'Blog Handle',
    type: 'text',
  },
  {
    id: '6',
    inputType: 'input',
    placeholder: 'Enter Tags',
    name: 'blog_tags',
    label: 'Blog Tags',
    type: 'text',
  },
  {
    id: '7',
    inputType: 'input',
    placeholder: 'Enter Template Suffix',
    name: 'blog_template_suffix',
    label: 'Blog Template Suffix',
    type: 'text',
  },
  {
    id: '8',
    inputType: 'input',
    placeholder: 'Add Metafield JSON',
    name: 'blog_metafield',
    label: 'Blog Metafield',
    type: 'text',
    multiline: true,
    rows: 4,
  },
  {
    id: '9',
    inputType: 'input',
    placeholder: 'Enter Article Title',
    name: 'article_title',
    label: 'Article Title',
    maxLength: 100,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '10',
    inputType: 'input',
    placeholder: 'Enter Author Name',
    name: 'article_author',
    label: 'Article Author',
    maxLength: 50,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '11',
    inputType: 'input',
    placeholder: 'Enter Article Content (HTML)',
    name: 'article_body_html',
    label: 'Article Body HTML',
    multiline: true,
    type: 'text',
    rows: 6,
  },
  {
    id: '12',
    inputType: 'input',
    placeholder: 'Enter Handle',
    name: 'article_handle',
    label: 'Article Handle',
    type: 'text',
  },
  {
    id: '13',
    inputType: 'input',
    placeholder: 'Enter Image URL',
    name: 'article_image',
    label: 'Article Image',
    type: 'text',
  },
  {
    id: '14',
    inputType: 'input',
    placeholder: 'Add Metafield JSON',
    name: 'article_metafield',
    label: 'Article Metafield',
    multiline: true,
    type: 'text',
    rows: 4,
  },
  {
    id: '15',
    inputType: 'checkbox',
    label: 'Article Published',
    name: 'article_published',
  },
  {
    id: '16',
    inputType: 'date',
    label: 'Article Published At',
    name: 'article_published_at',
  },
  {
    id: '17',
    inputType: 'input',
    placeholder: 'Enter Summary HTML',
    name: 'article_summary_html',
    label: 'Article Summary HTML',
    multiline: true,
    type: 'text',
    rows: 4,
  },
  {
    id: '18',
    inputType: 'input',
    placeholder: 'Enter Tags (comma-separated)',
    name: 'article_tags',
    label: 'Article Tags',
    type: 'text',
  },
  {
    id: '19',
    inputType: 'input',
    placeholder: 'Enter Template Suffix',
    name: 'article_template_suffix',
    label: 'Article Template Suffix',
    type: 'text',
  },
  {
    id: '20',
    inputType: 'input',
    placeholder: 'Input Data',
    label: 'Input Data',
    name: 'input_data',
    type: 'text',
  },
  {
    id: '21',
    inputType: 'input',
    placeholder: 'User Id',
    label: 'User Id',
    name: 'user_id',
    type: 'text',
  },
];

export const PRODUCT_FORM = [
  {
    id: '1',
    inputType: 'input',
    placeholder: 'Enter Product Title',
    name: 'title',
    label: 'Title',
    maxLength: 100,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '2',
    inputType: 'input',
    placeholder: 'Enter Product Type',
    name: 'product_type',
    label: 'Product Type',
    type: 'text',
  },
  {
    id: '3',
    inputType: 'input',
    placeholder: 'Enter Vendor Name',
    name: 'vendor',
    label: 'Vendor Name',
    type: 'text',
  },
  {
    id: '4',
    inputType: 'select',
    placeholder: 'Select Product Status',
    name: 'status',
    label: 'Status',
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Archived', value: 'archived' },
      { label: 'Draft', value: 'draft' },
    ],
  },
  {
    id: '5',
    inputType: 'input',
    placeholder: 'Enter Handle',
    name: 'handle',
    label: 'Handle',
    type: 'text',
  },
  {
    id: '6',
    inputType: 'input',
    placeholder: 'Enter Template Suffix',
    name: 'template_suffix',
    label: 'Template Suffix',
    type: 'text',
  },
  {
    id: '7',
    inputType: 'input',
    placeholder: 'Image URL',
    name: 'image',
    label: 'Image',
    type: 'text',
  },
  {
    id: '8',
    inputType: 'input',
    placeholder: 'Image URLs',
    name: 'images',
    label: 'Images',
    type: 'text',
  },
  {
    id: '9',
    inputType: 'input',
    placeholder: 'Enter Product Tags (comma-separated)',
    name: 'tags',
    label: 'Tags',
    type: 'text',
  },

  {
    id: '10',
    inputType: 'input',
    placeholder: 'Enter Options',
    name: 'options',
    label: 'Options',
    type: 'text',
    multiline: 4
  },
  {
    id: '11',
    inputType: 'input',
    placeholder: 'Enter Variants',
    name: 'variants',
    label: 'Variants',
    type: 'text',
    multiline: 4
  },
  {
    id: '12',
    inputType: 'input',
    placeholder: 'Enter Page Title',
    name: 'page_title',
    label: 'Page Title',
    type: 'text',
  },
  {
    id: '13',
    inputType: 'input',
    placeholder: 'Enter Meta Description',
    name: 'meta_description',
    label: 'Meta Description',
    type: 'text',
  },
  {
    id: '14',
    inputType: 'input',
    placeholder: 'Input Data',
    label: 'Input Data',
    name: 'input_data',
    type: 'text',
  },
];

export const PRODUCT_IMAGE_FORM = [
  {
    id: '1',
    inputType: 'input',
    placeholder: 'Enter Image Source URL',
    name: 'src',
    label: 'Image URL',
    type: 'text',
  },
  {
    id: '2',
    inputType: 'input',
    placeholder: 'Enter Alt Text',
    name: 'alt',
    label: 'Alt Text',
    type: 'text',
  },
  {
    id: '3',
    inputType: 'input',
    placeholder: 'Enter Image Position',
    name: 'position',
    label: 'Position',
    type: 'number',
  },
  {
    id: '4',
    inputType: 'input',
    placeholder: 'Enter Width',
    name: 'width',
    label: 'Width',
    type: 'number',
  },
  {
    id: '5',
    inputType: 'input',
    placeholder: 'Enter Height',
    name: 'height',
    label: 'Height',
    type: 'number',
  },
];

export const PRODUCT_VARIANT_FORM = [
  {
    id: '1',
    inputType: 'input',
    placeholder: 'Enter Variant Title',
    name: 'title',
    label: 'Title',
    maxLength: 100,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '2',
    inputType: 'input',
    placeholder: 'Enter SKU',
    name: 'sku',
    label: 'SKU',
    type: 'text',
  },
  {
    id: '3',
    inputType: 'input',
    placeholder: 'Enter Barcode',
    name: 'barcode',
    label: 'Barcode',
    type: 'text',
  },
  {
    id: '4',
    inputType: 'input',
    placeholder: 'Enter Price',
    name: 'price',
    label: 'Price',
    type: 'number',
    prefix: '$',
  },
  {
    id: '5',
    inputType: 'input',
    placeholder: 'Enter Compare At Price',
    name: 'compare_at_price',
    label: 'Compare At Price',
    type: 'number',
    prefix: '$',
  },
  {
    id: '6',
    inputType: 'input',
    placeholder: 'Enter Weight',
    name: 'weight',
    label: 'Weight',
    type: 'number',
    suffix: 'kg',
  },
  {
    id: '7',
    inputType: 'select',
    placeholder: 'Select Weight Unit',
    name: 'weight_unit',
    label: 'Weight Unit',
    options: [
      { label: 'kg', value: 'kg' },
      { label: 'g', value: 'g' },
      { label: 'lb', value: 'lb' },
      { label: 'oz', value: 'oz' },
    ],
  },
  {
    id: '8',
    inputType: 'input',
    placeholder: 'Enter Inventory Quantity',
    name: 'inventory_quantity',
    label: 'Inventory Quantity',
    type: 'number',
  },
  {
    id: '9',
    inputType: 'select',
    placeholder: 'Select Inventory Policy',
    name: 'inventory_policy',
    label: 'Inventory Policy',
    options: [
      { label: 'Continue', value: 'continue' },
      { label: 'Deny', value: 'deny' },
    ],
  },
  {
    id: '10',
    inputType: 'input',
    placeholder: 'Enter Fulfillment Service',
    name: 'fulfillment_service',
    label: 'Fulfillment Service',
    type: 'text',
  },
];

export const GENERIC_FORM: Array<{
  name: string;
  type: string;
  required: boolean;
}> = [
  {
    name: 'title',
    type: 'text',
    required: false,
  },
  {
    name: 'vendor',
    type: 'text',
    required: false,
  },
  {
    name: 'status',
    type: 'text',
    required: false,
  },
  {
    name: 'body_html',
    type: 'text',
    required: false,
  },
  {
    name: 'product_type',
    type: 'text',
    required: false,
  },
  {
    name: 'variants',
    type: 'array',
    required: false,
  },
  {
    name: 'options',
    type: 'array',
    required: false,
  },
  {
    name: 'pageTitle',
    type: 'text',
    required: false,
  },
  {
    name: 'metaDescription',
    type: 'text',
    required: false,
  },
  {
    name: 'handle',
    type: 'text',
    required: false,
  },
  {
    name: 'tags',
    type: 'text',
    required: false,
  },
  {
    name: 'image',
    type: 'text',
    required: false,
  },
  {
    name: 'template_suffix',
    type: 'text',
    required: false,
  },
  {
    name: 'images',
    type: 'array',
    required: false,
  },
  {
    name: 'blog_title',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_commentable',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_feedburner',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_feedburner_location',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_handle',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_tags',
    type: 'text',
    required: false,
  },
  {
    name: 'blog_template_suffix',
    type: 'text',
    required: false,
  },
  {
    name: 'article_title',
    type: 'text',
    required: false,
  },
  {
    name: 'article_author',
    type: 'text',
    required: false,
  },
  {
    name: 'article_body_html',
    type: 'text',
    required: false,
  },
  {
    name: 'article_handle',
    type: 'text',
    required: false,
  },
  {
    name: 'article_image',
    type: 'text',
    required: false,
  },
  {
    name: 'article_metafield',
    type: 'object',
    required: false,
  },
  {
    name: 'article_published_at',
    type: 'date',
    required: false,
  },
  {
    name: 'article_summary_html',
    type: 'text',
    required: false,
  },
  {
    name: 'article_tags',
    type: 'text',
    required: false,
  },
  {
    name: 'article_template_suffix',
    type: 'text',
    required: false,
  },
];

 export const PRODUCT_FORM_1 = [
  {
    id: '1',
    inputType: 'input',
    placeholder: 'Enter Product Title',
    name: 'title',
    label: 'Title',
    maxLength: 100,
    showCharacterCount: true,
    type: 'text',
  },
  {
    id: '2',
    inputType: 'textarea',
    placeholder: 'Enter Product Description (HTML)',
    name: 'body_html',
    label: 'Description',
    multiline: true,
    rows: 6,
  },
  {
    id: '3',
    inputType: 'input',
    placeholder: 'Enter Handle',
    name: 'handle',
    label: 'Handle',
    type: 'text',
  },
  {
    id: '4',
    inputType: 'input',
    placeholder: 'Enter Product Type',
    name: 'product_type',
    label: 'Product Type',
    type: 'text',
  },
  {
    id: '5',
    inputType: 'input',
    placeholder: 'Enter Vendor Name',
    name: 'vendor',
    label: 'Vendor',
    type: 'text',
  },
  {
    id: '6',
    inputType: 'select',
    placeholder: 'Select Product Status',
    name: 'status',
    label: 'Status',
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Archived', value: 'archived' },
      { label: 'Draft', value: 'draft' },
    ],
  },
  {
    id: '7',
    inputType: 'input',
    placeholder: 'Enter Product Tags (comma-separated)',
    name: 'tags',
    label: 'Tags',
    multiline: true,
    rows: 2,
  },
  {
    id: '8',
    inputType: 'input',
    placeholder: 'Enter Global Title Tag',
    name: 'metafields_global_title_tag',
    label: 'Global Title Tag',
    multiline: true,
    rows: 2,
  },
  {
    id: '9',
    inputType: 'input',
    placeholder: 'Enter Global Description Tag',
    name: 'metafields_global_description_tag',
    label: 'Global Description Tag',
    multiline: true,
    rows: 2,
  },
];

export const DEFAULT_VALUES: Record<string, any> = {
  title: 'Sample Product - Brand Name',
  vendor: 'Sample Vendor',
  status: 'active',
  body_html: '<p>This product solves your problem by providing a unique solution that adds value.</p>',
  product_type: 'Electronics',
  variants: [
    {
      id: 1,
      title: 'Default Variant',
      price: 100,
      sku: 'SKU001',
    },
  ],
  options: ['Size', 'Color'],
  pageTitle: 'Sample Product Page Title',
  metaDescription: 'This is a brief description of the sample product for search engines.',
  handle: 'sample-product-handle',
  tags: 'sample,product,brand,electronics',
  image: 'https://via.placeholder.com/150',
  template_suffix: 'default',
  images: [
    'https://via.placeholder.com/150',
    'https://via.placeholder.com/150',
  ],
  blog_title: 'Sample Blog Title',
  blog_commentable: 'yes',
  blog_feedburner: 'feedburner-url',
  blog_feedburner_location: 'feedburner-location',
  blog_handle: 'sample-blog-handle',
  blog_tags: 'blog,sample,post',
  blog_template_suffix: 'default',
  article_title: 'Sample Article Title',
  article_author: 'John Doe',
  article_body_html: '<p>This is the body of the sample article.</p>',
  article_handle: 'sample-article-handle',
  article_image: 'https://via.placeholder.com/150',
  article_metafield: {
    namespace: 'custom',
    key: 'field',
    value: 'Sample Meta Value',
  },
  article_published_at: new Date().toISOString(),
  article_summary_html: '<p>This is a brief summary of the sample article.</p>',
  article_tags: 'article,sample,news',
  article_template_suffix: 'default',
};
